import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  textDel: {
    fontSize: 20,
    fontWeight: 600,
    color: "gray",
  },
  box: {
    marginTop: 20,
    marginHorizontal: 20,
    backgroundColor: "#c3c3c3",
    height: 80,
    display: "flex",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    flexDirection: "row",
  },
  text1: {
    color: "#644AB5",
    fontSize: 25,
    fontWeight: 700,
  },
  text2: {
    color: "#644AB5",
    fontSize: 20,
  },
  boxRight: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    justifyContent: "space-evenly",
    flex: 1,
  },
  boxLeft: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    flex: 2,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 20,
  },
  centeredView2: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 50,
    marginHorizontal: 50,
  },
  modalView: {
    marginVertical: 100,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalView2: {
    marginVertical: 100,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    display: "flex",
    alignItems: "center",
    alignContent: "center",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
    marginLeft: 180,
    display: "flex",
    alignItems: "center",
    width: 40,
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },
  container: {
    flex: 1,
  },
  container2: {
    flex: 1,
    marginHorizontal: 20,
  },
  inner: {
    padding: 24,
    flex: 1,
  },
  inner2: {
    padding: 24,
    flex: 1,
  },
  header: {
    fontSize: 36,
    marginBottom: 48,
  },
  textInput: {
    height: 40,
    borderColor: "#000000",
    borderBottomWidth: 1,
    marginBottom: 36,
  },
  btnContainer: {
    backgroundColor: "white",
    marginTop: 12,
  },
  title_exit: {
    display: "flex",
    flexDirection: "row",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 20,
  },
  modalView: {
    marginVertical: 100,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    display: "flex",
    alignItems: "center",
    alignContent: "center",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
    marginLeft: 180,
    display: "flex",
    alignItems: "center",
    width: 40,
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },
  container: {
    flex: 1,
  },
  inner: {
    padding: 24,
    flex: 1,
  },
  header: {
    fontSize: 36,
    marginBottom: 48,
  },
  textInput: {
    height: 40,
    borderColor: "#000000",
    borderBottomWidth: 1,
    marginBottom: 36,
  },
  btnContainer: {
    backgroundColor: "white",
    marginTop: 12,
  },
  title_exit: {
    display: "flex",
    flexDirection: "row",
  },
  addIconContainer: {
    alignItems: "center",
    alignContent: "center",
    justifyContent: "center",
    display: "flex",
    flexDirection: "row",
  },
  addIcon: {
    marginVertical: 10,
  },
});
export default styles;
